FROM python:3.5.2
ADD all_in_one /all_in_one
WORKDIR /all_in_one/cron
RUN pip install -r requirements.txt
ENV PYTHONPATH=$PYTHONPATH:/

ADD all_in_one/cron/crontab /etc/cron.d/yn-cron
RUN chmod 0644 /etc/cron.d/yn-cron
RUN apt-get update
RUN apt-get -y install cron

RUN env |sed 's/^\(.*\)$/export \1/g' > /configs.sh